### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by besu** [tomdz/storm-esper#3]
I tried to build the jar file (I'm not using Maven for my project, so I just wanted to include storm-esper.jar in my IDE) using "mvn clean install" - here's the reults:

Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 11.976 sec <<< FAILURE!

Results :

Failed tests:   testMultipleSpoutsWithoutInputAlias(org.tomdz.storm.esper.StormEsperTest): Sets differ: expected [Event[componentId='bolt5A', streamId='default', type='null', data=[1, 4]]] but got []
  testSimple(org.tomdz.storm.esper.StormEsperTest): Sets differ: expected [Event[componentId='bolt1A', streamId='default', type='null', data=[4, 10]]] but got []

Tests run: 6, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] There are test failures.

Please refer to /home/besu/vm_shared/src/storm-esper/target/surefire-reports for the individual test results.
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16 seconds
[INFO] Finished at: Thu Aug 02 14:57:57 CEST 2012
[INFO] Final Memory: 40M/268M
[INFO] ------------------------------------------------------------------------

Some more detailed information taken from surefire-reports:

---
## Test set: org.tomdz.storm.esper.StormEsperTest

Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 11.976 sec <<< FAILURE!
testMultipleSpoutsWithoutInputAlias(org.tomdz.storm.esper.StormEsperTest)  Time elapsed: 0.155 sec  <<< FAILURE!
java.lang.AssertionError: Sets differ: expected [Event[componentId='bolt5A', streamId='default', type='null', data=[1, 4]]] but got []
    at org.testng.Assert.fail(Assert.java:89)
    at org.testng.Assert.assertEquals(Assert.java:694)
    at org.tomdz.storm.esper.StormEsperTest.runTest(StormEsperTest.java:98)
    at org.tomdz.storm.esper.StormEsperTest.testMultipleSpoutsWithoutInputAlias(StormEsperTest.java:191)
testSimple(org.tomdz.storm.esper.StormEsperTest)  Time elapsed: 0.158 sec  <<< FAILURE!
java.lang.AssertionError: Sets differ: expected [Event[componentId='bolt1A', streamId='default', type='null', data=[4, 10]]] but got []
    at org.testng.Assert.fail(Assert.java:89)
    at org.testng.Assert.assertEquals(Assert.java:694)
    at org.tomdz.storm.esper.StormEsperTest.runTest(StormEsperTest.java:98)
    at org.tomdz.storm.esper.StormEsperTest.testSimple(StormEsperTest.java:111)

**Comment by besu** [comment]
I managed to build the jar file using "mvn clean install -Dmaven.test.skip=true" though.

**Comment by tomdz** [comment]
I have an open issue in storm for this (https://github.com/nathanmarz/storm/issues/201). The tests run fine when run individually, but not when run all at once. Maybe this has been fixed in the just-released 0.8.0, I'll try this out soon.

Btw, you should run this as

```
mvn -DskipTests clean install
```

The difference is that `skipTests` will compile the tests but not run them whereas maven.test.skip will not even compile them.

**Comment by besu** [comment]
Didn't know that. Thank you =)
